### ISSUE TITLE
Webp quality

### ISSUE THREAD

**Issue by XenBG** [luchuanqi/vite-plugin-webp#2]
Hello! Is there a way to set quality for the generated Webp images?

Sharp seems to support this by `options.quality` - https://sharp.pixelplumbing.com/api-output#webp. The default value of `quality` is `80`.

**Comment by luchuanqi** [comment]
thanks for your using.  version 1.1.2 already supports

**Comment by XenBG** [comment]
Thanks, but you named it `shart`, not `sharp` in your last commit [cec855c](https://github.com/luchuanqi/vite-plugin-webp/commit/cec855c1297876006e7f23bb5749d49266f56c60).

**Comment by luchuanqi** [comment]
> Thanks, but you named it `shart`, not `sharp` in your last commit [cec855c](https://github.com/luchuanqi/vite-plugin-webp/commit/cec855c1297876006e7f23bb5749d49266f56c60).

done
